name: test runner
on:
    workflow_dispatch:
jobs:
    test_schedule:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: "20.x"
            - name: NPM install
              run: npm i
            - name: Run script
              run: node ./index.js
    
